# Ficheiro 1 - Atividade de Internamento Hospitalar

# ESTAÇÃO 3 — Guardar numa base de dados e consultar com SQL

O objetivo é guardar os dados de forma estruturada numa base de dados e realizar consultas SQL para explorar a informação.

## Análise da demória média de internamento por região

 Como gestor de uma unidade hospitalar, quero ver a demora média de internamento da minha região comparada com as restantes regiões de saúde, para identificar se o meu hospital está acima ou abaixo da média nacional.

In [ ]:
import sqlite3
import pandas as pd

df = pd.read_csv("../data/processed/atividade_de_internamento_tratado.csv", sep=",", encoding="utf-8-sig")

# Liga (ou cria) a base de dados SQLite
con = sqlite3.connect("../data/processed/internamento-hospital.db")

# df.to_sql escreve o DataFrame como uma TABELA dentro da base de dados.
# if_exists='replace' substitui a tabela se já existir; index=False não guarda o nº da linha.

df.to_sql("internamento", con, if_exists="replace", index=False)


q = """

SELECT regiao,        
ROUND(SUM(dias_internamento) / SUM(doentes_saidos)) AS demora_media_regiao
FROM internamento
WHERE doentes_saidos > 0
GROUP BY regiao
ORDER BY demora_media_regiao DESC;

"""
print(" ")
print("Demora média por região:")

display(pd.read_sql(q, con))

1ª QUERY | Analisar a demora média por região

                        regiao  demora_media_regiao
0   Região de Saúde do Algarve                 10.0
1          Região de Saúde LVT                  9.0
2     Região de Saúde do Norte                  8.0
3    Região de Saúde do Centro                  8.0
4  Região de Saúde do Alentejo                  8.0

## Análise da evolução dos dias de internamento ao longo do tempo 

Como responsável de planeamento da ACSS, quero ver a evolução dos dias de internamento ao longo do tempo (2015–2026), para perceber o impacto de eventos como a pandemia na capacidade hospitalar.

In [ ]:
q = """

SELECT SUBSTR(periodo, 1, 4) AS ano,     
ROUND(SUM(dias_internamento) / SUM(doentes_saidos)) AS demora_media
FROM internamento
WHERE doentes_saidos > 0
GROUP BY ano
ORDER BY ano;
"""

print("Evolução anual da demora média:")
display(pd.read_sql(q, con))

2ª QUERY | Analisar a evolução dos dias de internamento

     ano  demora_media
0   2015           8.0
1   2016           8.0
2   2017           8.0
3   2018           9.0
4   2019           9.0
5   2020           9.0
6   2021           9.0
7   2022           9.0
8   2023           9.0
9   2024           9.0
10  2025           9.0
11  2026           9.0